// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-3')['BAlert']
    BaseAlert: typeof import('./src/components/BaseAlert.vue')['default']
    BaseCommentDetail: typeof import('./src/components/comment/BaseCommentDetailForm.vue')['default']
    BaseCommentDetailForm: typeof import('./src/components/comment/BaseCommentDetailForm.vue')['default']
    BaseCommentForm: typeof import('./src/components/comment/BaseCommentForm.vue')['default']
    BaseCommentWrite: typeof import('./src/components/comment/BaseCommentWriteForm.vue')['default']
    BaseCommentWriteForm: typeof import('./src/components/comment/BaseCommentWriteForm.vue')['default']
    BaseLoading: typeof import('./src/components/BaseLoading.vue')['default']
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    BaseTitle: typeof import('./src/components/BaseTitle.vue')['default']
    BButton: typeof import('bootstrap-vue-3')['BButton']
    BCard: typeof import('bootstrap-vue-3')['BCard']
    BCardGroup: typeof import('bootstrap-vue-3')['BCardGroup']
    BCardImg: typeof import('bootstrap-vue-3')['BCardImg']
    BCardText: typeof import('bootstrap-vue-3')['BCardText']
    BCarousel: typeof import('bootstrap-vue-3')['BCarousel']
    BCarouselSlide: typeof import('bootstrap-vue-3')['BCarouselSlide']
    BCol: typeof import('bootstrap-vue-3')['BCol']
    BCollapse: typeof import('bootstrap-vue-3')['BCollapse']
    BContainer: typeof import('bootstrap-vue-3')['BContainer']
    BFormInput: typeof import('bootstrap-vue-3')['BFormInput']
    BFormRadioGroup: typeof import('bootstrap-vue-3')['BFormRadioGroup']
    BFormSelect: typeof import('bootstrap-vue-3')['BFormSelect']
    BNavbar: typeof import('bootstrap-vue-3')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-3')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-3')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-3')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-3')['BNavItem']
    BRow: typeof import('bootstrap-vue-3')['BRow']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TitleComponent: typeof import('./src/components/TitleComponent.vue')['default']
  }
}
