// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-3')['BAlert']
    BButton: typeof import('bootstrap-vue-3')['BButton']
    BCard: typeof import('bootstrap-vue-3')['BCard']
    BCardBody: typeof import('bootstrap-vue-3')['BCardBody']
    BCardFooter: typeof import('bootstrap-vue-3')['BCardFooter']
    BCardGroup: typeof import('bootstrap-vue-3')['BCardGroup']
    BCardImg: typeof import('bootstrap-vue-3')['BCardImg']
    BCardText: typeof import('bootstrap-vue-3')['BCardText']
    BCardTitle: typeof import('bootstrap-vue-3')['BCardTitle']
    BCarousel: typeof import('bootstrap-vue-3')['BCarousel']
    BCarouselSlide: typeof import('bootstrap-vue-3')['BCarouselSlide']
    BCol: typeof import('bootstrap-vue-3')['BCol']
    BCollapse: typeof import('bootstrap-vue-3')['BCollapse']
    BContainer: typeof import('bootstrap-vue-3')['BContainer']
    BDropdownDivider: typeof import('bootstrap-vue-3')['BDropdownDivider']
    BDropdownItem: typeof import('bootstrap-vue-3')['BDropdownItem']
    BFormInput: typeof import('bootstrap-vue-3')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-3')['BFormInvalidFeedback']
    BFormTags: typeof import('bootstrap-vue-3')['BFormTags']
    BFormText: typeof import('bootstrap-vue-3')['BFormText']
    BImg: typeof import('bootstrap-vue-3')['BImg']
    BListGroup: typeof import('bootstrap-vue-3')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-3')['BListGroupItem']
    BNav: typeof import('bootstrap-vue-3')['BNav']
    BNavbar: typeof import('bootstrap-vue-3')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-3')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-3')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-3')['BNavbarToggle']
    BNavForm: typeof import('bootstrap-vue-3')['BNavForm']
    BNavItem: typeof import('bootstrap-vue-3')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-3')['BNavItemDropdown']
    BRow: typeof import('bootstrap-vue-3')['BRow']
    BTab: typeof import('bootstrap-vue-3')['BTab']
    BTabs: typeof import('bootstrap-vue-3')['BTabs']
    Content: typeof import('./src/components/Content.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    MenuBar: typeof import('./src/components/tiptap/MenuBar.vue')['default']
    MenuItem: typeof import('./src/components/tiptap/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    T: typeof import('./src/components/tiptap/T.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}
